### ISSUE TITLE
NEED SUPPORT ASAP!

### ISSUE THREAD

**Issue by mike8881** [projectskyhook/skyhook#32]
Hi Skyhook community, I am currently stuck with a big issue. I own a USD/SKYHOOK in Canada.

I need to find out how I can switch the software and the cash acceptor to make it work or if there's a solution for this. I need more informations. @jonhannis does not reply most of the times. I've been having a really hard time with this machine and now this issue pops up. PS I bought it from craigslist so I really don't have papers for it or any kind of refference number.

Need help.

**Comment by mike8881** [comment]
Hello @jonhannis

**Comment by mike8881** [comment]
How can I change the sd image to CAD and what can I do for the bill acceptor since I currently own a USD bill acceptor and I'm in need of a CAD!

**Comment by mike8881** [comment]
@jonhannis

**Comment by jonhannis** [comment]
The bill acceptor in the USD unit is not compatible with CAD firmware, unfortunately.

**Comment by mike8881** [comment]
Okay, what if I just end you the USD bill acceptor and you send me a CAD
bill acceptor or what if I just order from pyramid tech inc... Please write
me back and can you send me the Cad Firmware and some instructions to
switch to it...

**Comment by mike8881** [comment]
Okay, what if I just end you the USD bill acceptor and you send me a CAD bill acceptor or what if I just order from pyramid tech inc... Please write me back and can you send me the Cad Firmware and some instructions to switch to it... @jonhannis

**Comment by RandomMinds** [comment]
You come in here with an attitude like that. Go pound sand loser.

**Comment by mike8881** [comment]
@randomminds Do you have any idea how much time I've put in setting up this machine? You know very well yourself that the support for the skyhook is not that well. If you don't understand my situation then that's not a problem but keep your comments to yourself since it really does not help my issue at all. This is a place to help eachother. If I have offended you I am sorry but if you can't help me don't even write back.

**Comment by RandomMinds** [comment]
You are right. This is a place to help each other. But you came in here
attacking the entire community. If you want to help will help. But none of
us are paid to help you we are here because we wanted to be. You came in
here like you're entitled. You are not. Talk to us with respect and we will
respond in kind. Otherwise leave. And go find some other software.

**Comment by mike8881** [comment]
@randomminds Allright let's have a new start then. I really got shocked when I found out that I own a USD skyhook in Canada. I'm thinking maybe I can order the cad bill acceptor from @Jonhannis or pyramid tech inc or even switch my usd for a cad bill acceptor with Jon... I would really appreciate if someone explained me how to install a cad firmware or where to get it from... I am kind of lost right now... Thanks

**Comment by meZee** [comment]
@RandomMinds, I fail to see how anyone here has an attitude, perhaps you misunderstood @mike8881? He is asking a valid question, albeit not in the best way(incorrect issue title). I think his question deserves to be answered, and it was succinctly answered by @jonhannis . Now he's asking if he can use a CAD bill acceptor in place of the USD acceptor, and if he can get the CAD firmware, a totally valid question. Relax and take a second to sympathize, how you approached his question may come off as an appaling example of support, when in reality it is just a misunderstanding, and might make people think twice about getting behind Skyhook if that is to be expected.

**Comment by RandomMinds** [comment]
He said he wanted to "end us". That is not a valid way of asking for help.
That is a threat.

**Comment by RandomMinds** [comment]
OK... Looks like that may have been a typo and not what he meant. I deeply
apologise if I misunderstood.

**Comment by mike8881** [comment]
Send*** @jonhannis @randomminds @mezee lol can anyone please help me?
